#!/usr/bin/env python3
"""Collection mode: scan each subdirectory of a monorepo as its own system.

A samples/examples monorepo is not one architecture, so a single repo-level
badge is misleading. This tool scans each immediate subdirectory of --root
independently, writes a badge + evidence JSON per sample, and generates a
markdown report table that serves as the collection's architecture map.

Usage:
  python tools/scan_collection.py --root samples/python/agents \\
      --rules agentic-pattern-rules.yaml --out .github/agentic

Outputs (under --out):
  badges/<sample>.svg      per-sample badge
  scans/<sample>.json      per-sample evidence file
  REPORT.md                index table (embed or link from the repo README)

Samples with no detected patterns are listed in the report but get no badge
(never guess). Directories without Python files are skipped entirely.
"""

import argparse
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent


def load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True, help="Directory whose children are samples")
    ap.add_argument("--rules", default=str(HERE / "agentic-pattern-rules.yaml"))
    ap.add_argument("--out", default=".github/agentic")
    ap.add_argument("--repo-url", default="", help="Base URL for evidence links in the report")
    args = ap.parse_args()

    root, out = Path(args.root), Path(args.out)
    (out / "badges").mkdir(parents=True, exist_ok=True)
    (out / "scans").mkdir(parents=True, exist_ok=True)

    scanner = load_module("appl_scanner", HERE / "scanner.py")
    badge = load_module("appl_badge", HERE / "badge.py")
    import yaml
    rules = yaml.safe_load(open(args.rules))

    rows = []
    for sample in sorted(p for p in root.iterdir() if p.is_dir()):
        if not any(sample.rglob("*.py")):
            continue
        deps = scanner.read_dependencies(sample)
        collectors = scanner.collect_repo_symbols(sample)
        fw, pmap = scanner.match_rules(rules, deps, collectors)
        scanner.match_config_signals(rules, sample, pmap, fw, dep_files=deps)
        result = scanner.build_result(sample, rules.get("meta", {}).get("schema_version", "?"), fw, pmap)

        name = sample.name
        patterns = result["patterns"]
        if patterns:
            (out / "scans" / f"{name}.json").write_text(json.dumps(result, indent=2))
            svg = badge.render(result, style="full")
            (out / "badges" / f"{name}.svg").write_text(svg)
        rows.append((name, patterns, [f["id"] for f in result["frameworks"]]))

    lines = [
        "# Agentic Architecture Report",
        "",
        f"Per-sample architectural patterns detected under `{args.root}`, "
        "per the taxonomy in *Architectural Patterns for Agentic AI Systems* "
        "([agenticprotocols.dev](https://agenticprotocols.dev)). "
        "Every badge links to a scan file citing file:line evidence for each claim.",
        "",
        "| Sample | Patterns | Frameworks | Evidence |",
        "|---|---|---|---|",
    ]
    for name, patterns, fws in rows:
        if patterns:
            badge_cell = f"[![{name}](badges/{name}.svg)](scans/{name}.json)"
            plist = ", ".join(f"`{p['id']}`" for p in patterns)
            evid = f"[scan](scans/{name}.json)"
        else:
            badge_cell, plist, evid = f"`{name}`", "*none detected*", "—"
        fwcell = ", ".join(fws) if fws else "—"
        lines.append(f"| {badge_cell} | {plist} | {fwcell} | {evid} |")
    lines += [
        "",
        f"*Generated by [agentic-pattern-linter](https://github.com/akshar100/agentic-patterns); "
        f"{sum(1 for _, p, _ in rows if p)}/{len(rows)} samples with detected patterns.*",
    ]
    (out / "REPORT.md").write_text("\n".join(lines) + "\n")
    print(f"{sum(1 for _, p, _ in rows if p)}/{len(rows)} samples with patterns -> {out}/REPORT.md")


if __name__ == "__main__":
    main()
